ruby_and_rails_quiz/Blog_Post/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  root "posts#index"

end

ruby_and_rails_quiz/Blog_Post/app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new
 
    can :manage, Post do |post|
      post.user == user
    end
 
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

ruby_and_rails_quiz/Blog_Post/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby_and_rails_quiz/Blog_Post/app/models/post.rb
class Post < ApplicationRecord
    validates(
        :author,
        presence: { message: "author must exist" },
        uniqueness: true,
        length: { minimum: 3 }
    )
    validates(
        :body,
        presence: { message: "must exist" },
        length: { minimum: 20 }
    )
end

# Model => A Rails Model is a Ruby class that can add database records (think of whole rows in an Excel table), find particular data you're looking for, update that data, or remove data. ... Rails contains a model generator, which you can use via your command line, as long as you're in a Rails app already. in this we add some vadilations to our app like author must have altleast 3 alphabets and body should have atleast 20 alphabets.It is generated by rails g model <Name of the model>

ruby_and_rails_quiz/Blog_Post/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness: true, format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
 
end

ruby_and_rails_quiz/Blog_Post/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user!
        redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
      end
     
      def user_signed_in?
        current_user.present?
      end
      helper_method :user_signed_in?
     
      def current_user
        @current_user ||= User.find_by_id session[:user_id]
      end
      helper_method :current_user
end

ruby_and_rails_quiz/Blog_Post/app/controllers/posts_controller.rb
class PostsController < ApplicationController  
  before_action :find_post, only: [:show, :edit, :update, :destroy]   
  before_action :authenticate_user!, except: [:index, :show]
    def index
      @posts = Post.all
    end
   
    def new
      @post = Post.new
    end
   
    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to posts_path, notice: "Post Created"
      else
        render :new
      end
    end
   
    def show
    end
   
    def edit
      redirect_to root_path, alert: "access defined" unless can? :edit, @post

    end
   
    def update
      redirect_to root_path, alert: "access defined" unless can? :update, @post
      if @post.update post_params
        redirect_to @post, notice: "Post Updated"
    else
        render :edit
      end
    end
    def destroy
      redirect_to root_path, alert: "access defined" unless can? :destroy, @post
      @post.destroy
      redirect_to posts_path, notice: "Post Deleted"
    end
   
    private
   
    def find_post
      @post = Post.find params[:id]
    end

    def post_params
        params.require(:post).permit(:author, :body)
    end
   
  end

# Controller =>The controller is the logical center of your application. It coordinates the interaction between the user, the views, and the model. The controller is also a home to a number of important ancillary services. It is responsible for routing external requests to internal actions.In this controller we create,show,edit,update the posts and also making a new post.It is generated by rails g controller <Name of controller>

ruby_and_rails_quiz/Blog_Post/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
    def new
    end
   
    def create
      @user = User.find_by_email params[:email]
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Logged in"
      else
        flash[:alert] = "Wrong email or password"
        render :new
      end
    end
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
      end
  end

ruby_and_rails_quiz/Blog_Post/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
   
    def create
      @user = User.new user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Logged In!"
      else
        render :new
      end
    end
   
    private
   
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
  end

ruby_and_rails_quiz/Blog_Post/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_and_rails_quiz/Blog_Post/app/helpers/posts_helper.rb
module PostsHelper
end

ruby_and_rails_quiz/Blog_Post/app/helpers/sessions_helper.rb
module SessionsHelper
end

ruby_and_rails_quiz/Blog_Post/app/helpers/users_helper.rb
module UsersHelper
end

ruby_and_rails_quiz/Blog_Post/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
        <% if user_signed_in? %>
    Hello <%= current_user.first_name %>,
    <%= link_to "Logout", sessions_path, method: :delete,
             data: {confirm: "are you sure you want to log out?"}%>
  <% else %>
    <%= link_to "Login", new_session_path %> |
    <%= link_to "Sign Up", new_user_path %>
  <% end %>
  <hr>
      <%= render 'shared/navbar' %>
   <div class='container'>
      <% flash.each do |type, message| %>
        <div class='bg-<%= type %> p-3 rounded mb-2 shadow-sm'>
          <%= message %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

ruby_and_rails_quiz/Blog_Post/app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @post do |f| %>
  <div>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

ruby_and_rails_quiz/Blog_Post/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render "form" %>

ruby_and_rails_quiz/Blog_Post/app/views/posts/index.html.erb
<h1>All Posts</h1>
 
<% @posts.each do |post|  %>
  <div>
    <h2><%= link_to post.author, post_path(post) %></h2>
    <p><%= post.body %></p>
    <hr>
  </div>
<% end %>

ruby_and_rails_quiz/Blog_Post/app/views/posts/new.html.erb
<h1>Create New Post</h1>
 
<%= render "form" %>

ruby_and_rails_quiz/Blog_Post/app/views/posts/show.html.erb
<h1><%= @post.author %></h1>
 
<p><%= @post.body %></p>
 
<p><%= @post.created_at %></p>

  <% if can? :edit, @post %>
  <%= link_to "Edit", edit_post_path(@post) %>
<% end %>
<% if can? :destroy, @post %>
  <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

ruby_and_rails_quiz/Blog_Post/app/views/shared/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-light'>
  <ul class='navbar-nav mr-auto'>
    <%# link_to 'Question Index', '/questions' %>
    <%= link_to 'Post Index', posts_path %>
    |
    <%= link_to 'Post New Page', new_post_path %>
    
  </ul>
 
</nav>

ruby_and_rails_quiz/Blog_Post/app/views/users/new.html.erb
<h1>Sign Up</h1>
 
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
 
<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>